### ISSUE TITLE
where do i find it

### ISSUE THREAD

**Issue by leyestd** [omnilight/yii2-shopping-cart#11]
I can't find EVENT corresponding method

$this->trigger(self::EVENT_POSITION_PUT, new Event([
            'data' => $this->_positions[$position->getId()],
 ]));

**Comment by omnilight** [comment]
Please, give more description about your problem

**Comment by leyestd** [comment]
teacher helps me 
here ,I only see the triggering event, the corresponding method is not found And not be attached .
Is this code  only used to respond to behavior method?

    public function onPutPosition($event)
    {
    	var_dump($event);
    	die();
    }

result
 public 'data' => null 

why

**Comment by omnilight** [comment]
Probably you have some proglems with event triggering, show more of your code
