### ISSUE TITLE
Remove item

### ISSUE THREAD

**Issue by drSun** [omnilight/yii2-shopping-cart#14]
Hi! Thank you for your cool shopping cart :) 
I'm not sure, but there is a bug in method
```
    /**
     * Removes position from the cart
     * @param CartPositionInterface $position
     */
    public function remove($position)
    {
        $this->removeById($position->id);
    }
```
There should be $position->getId() instead of $position->id, because in case of composite id such as md5(serialize([$this->id, $this->price, $this->color])) you cannot properly remove item from cart just by $this->id.

Maybe I'm wrong, of course. Anyway thank you for reading all that above!

**Comment by omnilight** [comment]
Yes, you are right, closed with a353090bd8db052fcda677df543d4b268753d1b0
Thank you.
