### ISSUE TITLE
EVENT_CART_CHANGE triggered at wrong place in ShoppingCart::removeById()

### ISSUE THREAD

**Issue by mhs135** [omnilight/yii2-shopping-cart#15]
On ShoppingCart::removeById(), the event 'EVENT_CART_CHANGE' should be triggered only after the unset of that position. Now, it gets triggered before the removal of that position.

**Comment by omnilight** [comment]
Why? This event takes `action` property, which has `CartActionEvent::ACTION_BEFORE_REMOVE`

**Comment by mhs135** [comment]
EVENT_CART_CHANGE should be triggered only after some changes has happened to the cart.
So, the method should be like:

    public function removeById($id)
    {    
        $this->trigger(self::EVENT_BEFORE_POSITION_REMOVE, new CartActionEvent([
            'action' => CartActionEvent::ACTION_BEFORE_REMOVE,
            'position' => $this->_positions[$id],
        ]));
        unset($this->_positions[$id]);
        $this->trigger(self::EVENT_CART_CHANGE, new CartActionEvent([
            'action' => CartActionEvent::ACTION_BEFORE_REMOVE,
            'position' => $this->_positions[$id],
        ]));
        if ($this->storeInSession)
            $this->saveToSession();
    }

I had a situation where the same case occurred and I extended the class and overrode this method as above.
Anyway, nice extension, well done!

**Comment by omnilight** [comment]
It is possible not to use EVENT_CART_CHANGE, but create events like EVENT_BEFORE_CART_CHANGE, EVENT_AFTER_CART_CHANGE, and trigger them before and after change.
