### ISSUE TITLE
Better Documentation???

### ISSUE THREAD

**Issue by DreadfulCode** [omnilight/yii2-shopping-cart#19]
Title sums it up.

I get a "Class 'app\controllers\ShoppingCart' not found" immediately.

And sure enough I was missing a:

    use yz\shoppingcart\ShoppingCart;

At the top of the controller. 

There isn't even a whisper of such a line anywhere in the examples. An small working example utilizing this library would help immensely and gain more developers.

**Comment by omnilight** [comment]
Could you provide pull-request?

**Comment by DreadfulCode** [comment]
Sure.

**Comment by DreadfulCode** [comment]
I'll be happy to provide a better readme on top of what's already in place.

**Comment by omnilight** [comment]
Ok :)
