### ISSUE TITLE
Serialization of Closure issue

### ISSUE THREAD

**Issue by fxpage** [omnilight/yii2-shopping-cart#24]
I got this issue in line 122 of ShoppingCart.php.

'Exception 'Exception' with message 'Serialization of 'Closure' is not allowed' 

in /Volumes/MACDATA/Work/Aljazeera/vendor/omnilight/yii2-shopping-cart/ShoppingCart.php:122'

Please review the code and it would be great if you can handle this exception.

**Comment by omnilight** [comment]
Can you more code from your application? Where you use closure?

**Comment by fxpage** [comment]
I have used your cart as global application component.

when I run the code `\Yii::$app->cart->put($model, 1);` in my viewcontroller, it throws the exception.
