### ISSUE TITLE
Same Product with different options

### ISSUE THREAD

**Issue by zoocreative** [omnilight/yii2-shopping-cart#27]
Hi,
How to I add a product to the cart with the same ID but with different options for price etc.

I have set the CartPositionProviderInterface as directed in the readme but I really don't know where to go from there as I don't see any change in how the cart is stored or the variables contained within it.
Thanks

**Comment by re8us** [comment]
You should read README again:

> This way gives us ability to create separate cart positions for the same product, that differs only on some property, for example price or color:

```
// app\models\ProductCartPosition.php

class ProductCartPosition extends Object implements CartPositionInterface
{
    public $id;
    public $price;
    public $color;

    //...
    public function getId()
    {
        return md5(serialize([$this->id, $this->price, $this->color]));
    }

    //...
}
```

>
