### ISSUE TITLE
Yii2 shopping cart doesn't save to session

### ISSUE THREAD

**Issue by fxpage** [omnilight/yii2-shopping-cart#28]
I'm using Yii2 for my e-commerce website.
Here I'm using omnilight/yii2-shopping-cart, but I am not sure why it does not save to session product's information.

I have used ajax request to put my product to shopping cart position.

'function actionAddToCart() {

    $pid = $_REQUEST['pid'];
    $quantity = $_REQUEST['quantity'];

    $model = Product::findOne($pid);
    $model->quantity = $quantity;

    if ($model) {
        // @@@ Add Cookie Data here
        $cart = \Yii::$app->cart;

        $params = [];
        $params['price'] = $model->price;
        $params['quantity'] = $quantity;

        $cartPosition = $model->getCartPosition($params);

        $cart->put($cartPosition, $quantity);

        // var_dump($cart);
        // die();

        return $this->renderAjax('productView', [
            'product' => $model
        ]);
    }
}'
When I get log of cart here, I can see that the product added to session.
But after loading productView, I am seeing that there is no product in the session.

Any help would be appreciated.

**Comment by omnilight** [comment]
Why you do not pass `$cart` to the `productView`? How do you check for session in the view?

**Comment by fxpage** [comment]
I got $cart from productView like in controller. 
 <span id="cart-amount-lbl"><?=\Yii::$app->cart->getCount();?></span>
but it returning 0.

**Comment by fxpage** [comment]
Here I'm using CartPositionInterface which have id, price, color, size, length, quantity as it's parameters.
