### ISSUE TITLE
Error when put into cart

### ISSUE THREAD

**Issue by howardEagle** [omnilight/yii2-shopping-cart#30]
Exception 'Exception' with message 'Serialization of 'Closure' is not allowed'

**Comment by omnilight** [comment]
Closures are not alowed to be serialized, but if you save your cart into session - it must be serialized. So if you want to use closures you must implement your own storage mechanic for the cart either via disabling session usage with storeInSession=false or via your own subclass of the cart that will override getSerialized method of original class
