### ISSUE TITLE
bad timing when triggering events in removeById

### ISSUE THREAD

**Issue by Slayvin** [omnilight/yii2-shopping-cart#38]
First there is a problem with the const name itself:
https://github.com/omnilight/yii2-shopping-cart/blob/76f785e278f403fbac6b1b59d8d15d83345533d5/ShoppingCart.php#L29-L30
The comment says it's triggered on **after**, but the const name is EVENT_**BEFORE**_POSITION_REMOVE
I think it's fine to trigger before, just change the comment please ;)

Then in this method:
https://github.com/omnilight/yii2-shopping-cart/blob/76f785e278f403fbac6b1b59d8d15d83345533d5/ShoppingCart.php#L167-L180

The position is removed (line 177) after both events are triggered, which imo makes one of them useless. 
The position should be removed right after the EVENT_BEFORE_POSITION_REMOVE is triggered, and right before
the EVENT_CART_CHANGE is triggered (and then the action also needs to be changed)

**Comment by omnilight** [comment]
Please, provide PR with requested change. I agree about comment mistake, but not with EVENT_CART_CHANGE position. Reason for the last is that this event was introduced earlier than EVENT_BEFORE_POSITION_REMOVE and now stays only for backward compatibility
