### ISSUE TITLE
Is it possible to declare a Quantity ?

### ISSUE THREAD

**Issue by thyseus** [omnilight/yii2-shopping-cart#44]
Can I set a quantity ?

For example "I want to buy this item three times" ? 

Net prices would be needed to calculate and possible tax afterwards.

**Comment by tensajougan8** [comment]
I have also been facing the same issue. And also how do i increase the quantity for each item?

**Comment by omnilight** [comment]
Quantity property exists inside items. https://github.com/omnilight/yii2-shopping-cart/blob/master/ShoppingCart.php#L99
