### ISSUE TITLE
Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by anashasabelnabi** [omnilight/yii2-shopping-cart#45]
i dont understand what is happened its work simply perfect and suddenly this exception thrown when i call function add to cart

**Comment by omnilight** [comment]
Need more information

**Comment by ArtMin96** [comment]
Same here.

```php
$cart = Yii::$app->cart;
$count = $post['count'];
$product = Product::findOne($post['prod_id']);

$cart->put($product, (int) $count);
```

**Comment by ArtMin96** [comment]
Fixed, I have custom validation in the model. But I think it should be working because I want to validate fields too.

**Comment by omnilight** [comment]
If cart model has validation that uses closures, you will get an error, because closure as a value of a field could not be serialized

**Comment by ArtMin96** [comment]
```php
'price', function($attribute, $params) {
                    if (!$this->standard_price) {
                        $this->addError($attribute, 'Credit amount should less than Bill amount.');
                        return false;
                    }
                }
```

here's the anonymous function.
