### ISSUE TITLE
tried to execute a method or access a property of an incomplete object

### ISSUE THREAD

**Issue by Slick335** [omnilight/yii2-shopping-cart#8]
Hey hey,

I just stumbled across your cart and wanted to use this extension.
I'm new to yii2 so I thought maybe it's easier to use this extension than programming it all by myself but I always get this error:

yz\shoppingcart\ShoppingCart::getCount(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition &quot;common\models\Article&quot; of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition

**Comment by omnilight** [comment]
Hello,

Given error string means that your class can not be autoloaded. Probably, you are trying to access your model before autoload register.
